---
- name: Check remi status
  shell: yum-config-manager remi | grep -q 'enabled = True'
  changed_when: False
  ignore_errors: True
  register: remi_status

- name: Install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Enabled remi
  command: yum-config-manager --enable remi
